name: eyeassist
description: A Flutter app for visually impaired users
version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  image_picker: ^1.1.1
  flutter_tts: ^4.2.3
  speech_to_text: ^7.1.0
  google_mlkit_text_recognition: ^0.12.0
  path_provider: ^2.1.3
  camera: ^0.10.5+9
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # your icon path